"use strict";
/**
 * Local stand-in for Groq's chat-completions endpoint.
 *
 * Lets the whole app be run, demoed and browser-tested without an API key and
 * without spending free-tier quota. Point the server at it:
 *
 *     node scripts/mock-groq.js &                       # listens on 8471
 *     GROQ_API_KEY=mock \
 *     GROQ_URL=http://127.0.0.1:8471/v1/chat/completions \
 *     npm start
 *
 * or simply `npm run dev:mock`, which does both.
 *
 * It returns a deterministic, schema-valid design. The response varies a little
 * with the prompt so that "generate" and a follow-up "modify" are visibly
 * different in the UI. It is NOT a model — it does not interpret the prompt.
 */
const http = require("http");

const PORT = Number(process.env.MOCK_PORT || 8471);

/** Deterministic 32-bit hash so the same prompt always yields the same design. */
function hash(str) {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

const PALETTES = [
  ["#0b1020", "#3b82f6", "#f472b6", "#fde68a"],
  ["#1a0b20", "#a855f7", "#22d3ee", "#fca5a5"],
  ["#101a10", "#22c55e", "#eab308", "#f8fafc"],
  ["#20140b", "#f97316", "#facc15", "#fef3c7"],
];

function design(prompt, isModify) {
  const h = hash(prompt || "default");
  const pal = PALETTES[h % PALETTES.length];
  const shift = isModify ? 40 : 0;
  return {
    frame: {
      name: isModify ? "Mock Modified" : "Mock Design",
      w: 900,
      h: 600,
      bg: pal[0],
      children: [
        {
          type: "rect",
          name: "Backdrop",
          x: 60,
          y: 60 + shift,
          w: 480,
          h: 300,
          radius: 24,
          opacity: 1,
          fill: {
            kind: "linear",
            angle: 35,
            stops: [
              { pos: 0, color: pal[1] },
              { pos: 1, color: pal[2] },
            ],
          },
        },
        {
          type: "ellipse",
          name: "Orb",
          x: 560,
          y: 120 + shift,
          w: 260,
          h: 260,
          opacity: 0.95,
          fill: {
            kind: "radial",
            stops: [
              { pos: 0, color: pal[3] },
              { pos: 1, color: pal[2] },
            ],
          },
          effects: { shadow: { on: true, x: 0, y: 14, blur: 34, alpha: 0.35 } },
        },
        {
          type: "ellipse",
          name: "Dot",
          x: 60,
          y: 400 + shift,
          w: 90,
          h: 90,
          opacity: 1,
          fill: {
            kind: "radial",
            stops: [
              { pos: 0, color: pal[3] },
              { pos: 1, color: pal[1] },
            ],
          },
          // Exercises the linked-pattern path end to end without a real model.
          pattern: {
            columns: isModify ? 3 : 5,
            rows: isModify ? 2 : 1,
            hGap: 18,
            vGap: 18,
            baseScale: 1,
            widthVariation: 0,
            heightVariation: 0,
            baseRotation: 0,
            rotationStep: isModify ? 15 : 0,
            mirror: "none",
            holes: 0,
            seed: h % 99999999 || 1,
          },
        },
        {
          type: "text",
          name: "Headline",
          x: 60,
          y: 530,
          text: isModify ? "Modified by mock" : "Generated by mock",
          size: 52,
          weight: 800,
          color: pal[3],
          align: "left",
        },
      ],
    },
  };
}

const server = http.createServer((req, res) => {
  if (req.method !== "POST") {
    res.writeHead(405, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: { message: "POST only" } }));
    return;
  }
  let raw = "";
  req.on("data", (c) => (raw += c));
  req.on("end", () => {
    let body = {};
    try {
      body = JSON.parse(raw);
    } catch {}
    const messages = body.messages || [];
    const user = messages[1] ? messages[1].content : "";
    const text = typeof user === "string" ? user : JSON.stringify(user);
    const isModify = text.includes("CURRENT DESIGN");

    const content = JSON.stringify(design(text, isModify));
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(
      JSON.stringify({
        choices: [{ message: { content } }],
        usage: { prompt_tokens: 100, completion_tokens: 200, total_tokens: 300 },
        model: body.model || "mock",
      }),
    );
  });
});

server.listen(PORT, "127.0.0.1", () =>
  console.log(`mock-groq listening on http://127.0.0.1:${PORT}/v1/chat/completions`),
);
